# Name of the workflow
name: Automated Update of NYPD Database From Multiple Sources

# Define the events that trigger the workflow
on:
  # Trigger the workflow on a schedule (every day at midnight UTC)
  schedule:
    - cron: "0 0 * * *" # Executes once every day at 00:00 UTC
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  # Define a job named "build"
  build:
    # Job name displayed in the GitHub Actions interface
    name: Update NYPD Database Files
    # Specify the type of runner to execute this job (Ubuntu-based runner)
    runs-on: ubuntu-latest
    # Define environment variables to be used across the steps
    env:
      # Full URLs for each file
      NYPD_DATABASE_50_A_ORG_OFFICERS_URL: https://www.50-a.org/data/nypd/officers.csv
      NYPD_DATABASE_50_A_ORG_OFFICERS_PATH: 50_A_ORG/nypd_officers.csv
      NYPD_DATABASE_50_A_ORG_RANKS_URL: https://www.50-a.org/data/nypd/ranks.csv
      NYPD_DATABASE_50_A_ORG_RANKS_PATH: 50_A_ORG/nypd_ranks.csv
      NYPD_DATABASE_50_A_ORG_DISCIPLINE_URL: https://www.50-a.org/data/nypd/discipline.csv
      NYPD_DATABASE_50_A_ORG_DISCIPLINE_PATH: 50_A_ORG/nypd_discipline.csv
      NYPD_DATABASE_50_A_ORG_DOCUMENTS_URL: https://www.50-a.org/data/nypd/documents.csv
      NYPD_DATABASE_50_A_ORG_DOCUMENTS_PATH: 50_A_ORG/nypd_documents.csv
      NYPD_DATABASE_50_A_ORG_TRAINING_URL: https://www.50-a.org/data/nypd/training.csv
      NYPD_DATABASE_50_A_ORG_TRAINING_PATH: 50_A_ORG/nypd_training.csv
      NYPD_DATABASE_50_A_ORG_AWARDS_URL: https://www.50-a.org/data/nypd/awards.csv
      NYPD_DATABASE_50_A_ORG_AWARDS_PATH: 50_A_ORG/nypd_awards.csv

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4 # Fetch the latest code from the repository

      # Install the required dependencies
      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install curl -y # Update package list and install curl

      # Download the NYPD officers file
      - name: Download NYPD officers file
        run: curl -L $NYPD_DATABASE_50_A_ORG_OFFICERS_URL -o $NYPD_DATABASE_50_A_ORG_OFFICERS_PATH

      # Download the NYPD ranks file
      - name: Download NYPD ranks file
        run: curl -L $NYPD_DATABASE_50_A_ORG_RANKS_URL -o $NYPD_DATABASE_50_A_ORG_RANKS_PATH

      # Download the NYPD discipline file
      - name: Download NYPD discipline file
        run: curl -L $NYPD_DATABASE_50_A_ORG_DISCIPLINE_URL -o $NYPD_DATABASE_50_A_ORG_DISCIPLINE_PATH

      # Download the NYPD documents file
      - name: Download NYPD documents file
        run: curl -L $NYPD_DATABASE_50_A_ORG_DOCUMENTS_URL -o $NYPD_DATABASE_50_A_ORG_DOCUMENTS_PATH

      # Download the NYPD training file
      - name: Download NYPD training file
        run: curl -L $NYPD_DATABASE_50_A_ORG_TRAINING_URL -o $NYPD_DATABASE_50_A_ORG_TRAINING_PATH

      # Download the NYPD awards file
      - name: Download NYPD awards file
        run: curl -L $NYPD_DATABASE_50_A_ORG_AWARDS_URL -o $NYPD_DATABASE_50_A_ORG_AWARDS_PATH

      # Commit and push the updated files
      - name: Push updated files
        run: |
          # Configure Git user details for the commit
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # If changes are detected, stage and commit the updated files
          git add .
          if ! git diff --cached --quiet; then
            # Commit the changes with a message that includes the current date
            git commit -m "Updated files on $(date)"  # Commit changes with a timestamped message
            # Push the committed changes to GitHub
            git push  # Push changes to the remote repository
          else
            echo "No changes to commit."  # Print message if no changes were detected
          fi  # End of conditional check for changes
